// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: text.module.css

export type TextAs = 'em' | 'p' | 'small' | 'span' | 'strong';
export type TextSize = '2xl' | 'base' | 'lg' | 'sm' | 'xl' | 'xs';
export type TextWeight = 'bold' | 'medium' | 'normal' | 'semibold';
export type TextIntent = 'black' | 'danger' | 'default' | 'gray' | 'primary' | 'secondary' | 'success' | 'warning' | 'white';
export type TextCase = 'capitalize' | 'lower' | 'upper';
export type TextTransform = 'line-through' | 'overline' | 'underline';

export interface TextDataAttrs {
  as?: TextAs;
  size?: TextSize;
  weight?: TextWeight;
  intent?: TextIntent;
  case?: TextCase;
  transform?: TextTransform;
};

export namespace Text {
  export type As = TextAs;
  export type Size = TextSize;
  export type Weight = TextWeight;
  export type Intent = TextIntent;
  export type Case = TextCase;
  export type Transform = TextTransform;
  export type DataAttrs = TextDataAttrs;
}
