// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: button-icon.module.css

export type ButtonIconSize = "large" | "medium" | "small";
export type ButtonIconVariant =
  | "danger"
  | "ghost"
  | "outline"
  | "primary"
  | "secondary";

export interface ButtonIconDataAttrs {
  size?: ButtonIconSize;
  variant?: ButtonIconVariant;
  disabled?: boolean;
  loading?: boolean;
}

export namespace ButtonIcon {
  export type Size = ButtonIconSize;
  export type Variant = ButtonIconVariant;
  export type DataAttrs = ButtonIconDataAttrs;
}
