// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
declare const styles: {
  readonly field: string;
  readonly indicator: string;
  readonly input: string;
  readonly option: string;
  readonly optionLabel: string;
  readonly options: string;
};
export default styles;
