// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: radio-group.module.css

export type RadioGroupDirection = 'row';

export interface RadioGroupDataAttrs {
  direction?: RadioGroupDirection;
};

export namespace RadioGroup {
  export type Direction = RadioGroupDirection;
  export type DataAttrs = RadioGroupDataAttrs;
}
