// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
declare const styles: {
  readonly body: string;
  readonly closeButton: string;
  readonly content: string;
  readonly footer: string;
  readonly header: string;
  readonly headerContent: string;
  readonly headerTop: string;
  readonly title: string;
};
export default styles;
