// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: overlay-parts.module.css

export interface OverlayPartsDataAttrs {
};

export namespace OverlayParts {
  export type DataAttrs = OverlayPartsDataAttrs;
}
