// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
declare const styles: {
  readonly sidebar: string;
  readonly 'sidebar-body': string;
  readonly 'sidebar-divider': string;
  readonly 'sidebar-footer': string;
  readonly 'sidebar-group': string;
  readonly 'sidebar-group-label': string;
  readonly 'sidebar-header': string;
  readonly 'sidebar-item': string;
  readonly 'sidebar-item-icon': string;
  readonly 'sidebar-item-text': string;
};
export default styles;
