// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: radio.module.css

export interface RadioDataAttrs {
  disabled?: boolean;
};

export namespace Radio {
  export type DataAttrs = RadioDataAttrs;
}
