// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: button-icon.module.css

export type ButtonIconSize = 'medium' | 'small';
export type ButtonIconVariant = 'danger' | 'ghost' | 'outline' | 'primary' | 'secondary';
export type ButtonIconLoadingIcon = 'loader';

export interface ButtonIconDataAttrs {
  size?: ButtonIconSize;
  variant?: ButtonIconVariant;
  loadingIcon?: ButtonIconLoadingIcon;
  disabled?: boolean;
  loading?: boolean;
};

export namespace ButtonIcon {
  export type Size = ButtonIconSize;
  export type Variant = ButtonIconVariant;
  export type LoadingIcon = ButtonIconLoadingIcon;
  export type DataAttrs = ButtonIconDataAttrs;
}
