// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: nav.module.css

export type NavDirection = 'horizontal' | 'vertical';

export interface NavDataAttrs {
  direction?: NavDirection;
  active?: boolean;
  disabled?: boolean;
  loading?: boolean;
};

export namespace Nav {
  export type Direction = NavDirection;
  export type DataAttrs = NavDataAttrs;
}
