// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: helper-text.module.css

export interface HelperTextDataAttrs {
};

export namespace HelperText {
  export type DataAttrs = HelperTextDataAttrs;
}
