// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: icon.module.css

export type IconSize = 'lg' | 'md' | 'sm' | 'xl' | 'xs';
export type IconIntent = 'danger' | 'ghost' | 'outline' | 'primary' | 'secondary';

export interface IconDataAttrs {
  size?: IconSize;
  intent?: IconIntent;
};

export namespace Icon {
  export type Size = IconSize;
  export type Intent = IconIntent;
  export type DataAttrs = IconDataAttrs;
}
