// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: button.module.css

export type ButtonIconConfig = 'both' | 'both-text' | 'left' | 'left-text' | 'right' | 'right-text';
export type ButtonSize = 'medium' | 'small';
export type ButtonVariant = 'danger' | 'ghost' | 'primary' | 'secondary';
export type ButtonLoadingIcon = 'loader';

export interface ButtonDataAttrs {
  iconConfig?: ButtonIconConfig;
  size?: ButtonSize;
  variant?: ButtonVariant;
  loadingIcon?: ButtonLoadingIcon;
  disabled?: boolean;
  loading?: boolean;
};

export namespace Button {
  export type IconConfig = ButtonIconConfig;
  export type Size = ButtonSize;
  export type Variant = ButtonVariant;
  export type LoadingIcon = ButtonLoadingIcon;
  export type DataAttrs = ButtonDataAttrs;
}
