// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: error-text.module.css

export interface ErrorTextDataAttrs {
};

export namespace ErrorText {
  export type DataAttrs = ErrorTextDataAttrs;
}
