// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: top-bar.module.css

export interface TopBarDataAttrs {
  active?: boolean;
  disabled?: boolean;
};

export namespace TopBar {
  export type DataAttrs = TopBarDataAttrs;
}
