services:
  storybook:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: versaur-storybook-dev
    ports:
      - "6006:6006"
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src:ro
      - ./assets:/app/assets:ro
      - ./.storybook:/app/.storybook:ro
      - ./package.json:/app/package.json:ro
      - ./yarn.lock:/app/yarn.lock:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - ./tailwind.config.ts:/app/tailwind.config.ts:ro
      - ./vite.config.ts:/app/vite.config.ts:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - STORYBOOK_PORT=6006
      - BROWSER=none
      - CI=true
      - NPM_TOKEN=
    networks:
      - versaur-network
    restart: unless-stopped

networks:
  versaur-network:
    driver: bridge
