services:
  storybook:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        NODE_ENV: production
        STORYBOOK_PORT: 8081
    container_name: versaur-storybook-prod
    environment:
      - NODE_ENV=production
      - STORYBOOK_PORT=8081
      - NPM_TOKEN=
    ports:
      - "8081:8081"
    networks:
      - versaur-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 150M
          cpus: "0.2"
        reservations:
          memory: 75M
          cpus: "0.1"

networks:
  versaur-network:
    driver: bridge
