// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: features.module.css

export type FeaturesDirection = 'column' | 'row';

export interface FeaturesDataAttrs {
  direction?: FeaturesDirection;
};

export namespace Features {
  export type Direction = FeaturesDirection;
  export type DataAttrs = FeaturesDataAttrs;
}
