// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: chip-multiple-input.module.css

export type ChipMultipleInputGap = '1' | '3' | '4';
export type ChipMultipleInputWrap = 'false';

export interface ChipMultipleInputDataAttrs {
  gap?: ChipMultipleInputGap;
  wrap?: ChipMultipleInputWrap;
  disabled?: boolean;
  selected?: boolean;
};

export namespace ChipMultipleInput {
  export type Gap = ChipMultipleInputGap;
  export type Wrap = ChipMultipleInputWrap;
  export type DataAttrs = ChipMultipleInputDataAttrs;
}
