// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: form-group.module.css

export interface FormGroupDataAttrs {
};

export namespace FormGroup {
  export type DataAttrs = FormGroupDataAttrs;
}
