// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: currency-input.module.css

export interface CurrencyInputDataAttrs {
  disabled?: boolean;
  focused?: boolean;
  invalid?: boolean;
  readOnly?: boolean;
};

export namespace CurrencyInput {
  export type DataAttrs = CurrencyInputDataAttrs;
}
