// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
declare const styles: {
  readonly 'amount-input': string;
  readonly 'currency-select': string;
  readonly divider: string;
  readonly field: string;
  readonly wrapper: string;
};
export default styles;
