// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: page-content.module.css

export interface PageContentDataAttrs {
};

export namespace PageContent {
  export type DataAttrs = PageContentDataAttrs;
}
