// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: app-layout.module.css

export type AppLayoutVariant = 'classic' | 'full' | 'mobile' | 'split';
export type AppLayoutShowHeader = 'false';
export type AppLayoutShowSideLeft = 'false';
export type AppLayoutShowSideRight = 'false';
export type AppLayoutShowBottom = 'false';

export interface AppLayoutDataAttrs {
  variant?: AppLayoutVariant;
  showHeader?: AppLayoutShowHeader;
  showSideLeft?: AppLayoutShowSideLeft;
  showSideRight?: AppLayoutShowSideRight;
  showBottom?: AppLayoutShowBottom;
};

export namespace AppLayout {
  export type Variant = AppLayoutVariant;
  export type ShowHeader = AppLayoutShowHeader;
  export type ShowSideLeft = AppLayoutShowSideLeft;
  export type ShowSideRight = AppLayoutShowSideRight;
  export type ShowBottom = AppLayoutShowBottom;
  export type DataAttrs = AppLayoutDataAttrs;
}
