// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
declare const styles: {
  readonly 'app-layout': string;
  readonly 'app-layout-bottom': string;
  readonly 'app-layout-header': string;
  readonly 'app-layout-main': string;
  readonly 'app-layout-side-left': string;
  readonly 'app-layout-side-right': string;
};
export default styles;
