// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: page-loader.module.css

export type PageLoaderType = 'bar' | 'spinner';
export type PageLoaderSize = 'lg' | 'sm';

export interface PageLoaderDataAttrs {
  type?: PageLoaderType;
  size?: PageLoaderSize;
};

export namespace PageLoader {
  export type Type = PageLoaderType;
  export type Size = PageLoaderSize;
  export type DataAttrs = PageLoaderDataAttrs;
}
