// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: chip-single-input.module.css

export type ChipSingleInputGap = '1' | '3' | '4';
export type ChipSingleInputWrap = 'false';

export interface ChipSingleInputDataAttrs {
  gap?: ChipSingleInputGap;
  wrap?: ChipSingleInputWrap;
  disabled?: boolean;
  invalid?: boolean;
  selected?: boolean;
};

export namespace ChipSingleInput {
  export type Gap = ChipSingleInputGap;
  export type Wrap = ChipSingleInputWrap;
  export type DataAttrs = ChipSingleInputDataAttrs;
}
