// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: badge-group.module.css

export type BadgeGroupGap = 'lg' | 'md' | 'sm' | 'xs';
export type BadgeGroupDirection = 'horizontal' | 'vertical';
export type BadgeGroupAlign = 'center' | 'end' | 'space-around' | 'space-between' | 'space-evenly' | 'start';
export type BadgeGroupWrap = 'nowrap' | 'wrap';

export interface BadgeGroupDataAttrs {
  gap?: BadgeGroupGap;
  direction?: BadgeGroupDirection;
  align?: BadgeGroupAlign;
  wrap?: BadgeGroupWrap;
};

export namespace BadgeGroup {
  export type Gap = BadgeGroupGap;
  export type Direction = BadgeGroupDirection;
  export type Align = BadgeGroupAlign;
  export type Wrap = BadgeGroupWrap;
  export type DataAttrs = BadgeGroupDataAttrs;
}
