// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: banner.module.css

export type BannerVariant = 'danger' | 'info' | 'warning';

export interface BannerDataAttrs {
  variant?: BannerVariant;
};

export namespace Banner {
  export type Variant = BannerVariant;
  export type DataAttrs = BannerDataAttrs;
}
