// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
declare const styles: {
  readonly banner: string;
  readonly close: string;
  readonly content: string;
  readonly icon: string;
};
export default styles;
