// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: hr.module.css

export type HrOrientation = 'horizontal' | 'vertical';
export type HrVariant = 'dashed' | 'dotted' | 'solid';
export type HrSize = 'lg' | 'md' | 'sm';
export type HrSpacing = 'lg' | 'md' | 'none' | 'sm' | 'xl';

export interface HrDataAttrs {
  orientation?: HrOrientation;
  variant?: HrVariant;
  size?: HrSize;
  spacing?: HrSpacing;
};

export namespace Hr {
  export type Orientation = HrOrientation;
  export type Variant = HrVariant;
  export type Size = HrSize;
  export type Spacing = HrSpacing;
  export type DataAttrs = HrDataAttrs;
}
