// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: text-input.module.css

export interface TextInputDataAttrs {
  disabled?: boolean;
  hasLeftIcon?: boolean;
  hasRightIcon?: boolean;
  invalid?: boolean;
  readOnly?: boolean;
};

export namespace TextInput {
  export type DataAttrs = TextInputDataAttrs;
}
