// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: menu.module.css

export interface MenuDataAttrs {
  active?: boolean;
  disabled?: boolean;
};

export namespace Menu {
  export type DataAttrs = MenuDataAttrs;
}
