// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: menu.module.css

export type MenuActive = 'true';

export interface MenuDataAttrs {
  active?: MenuActive;
};

export namespace Menu {
  export type Active = MenuActive;
  export type DataAttrs = MenuDataAttrs;
}
