// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
declare const styles: {
  readonly 'menu-item': string;
  readonly 'menu-item-icon': string;
  readonly 'menu-item-label': string;
  readonly 'menu-list': string;
};
export default styles;
