// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: dot.module.css

export type DotSize = 'medium' | 'small';
export type DotVariant = 'accent-1' | 'accent-2' | 'accent-3' | 'danger' | 'info' | 'primary' | 'secondary' | 'success' | 'warning';

export interface DotDataAttrs {
  size?: DotSize;
  variant?: DotVariant;
};

export namespace Dot {
  export type Size = DotSize;
  export type Variant = DotVariant;
  export type DataAttrs = DotDataAttrs;
}
