// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: attribute-list.module.css

export type AttributeListLayout = 'stacked' | 'tabular';

export interface AttributeListDataAttrs {
  layout?: AttributeListLayout;
};

export namespace AttributeList {
  export type Layout = AttributeListLayout;
  export type DataAttrs = AttributeListDataAttrs;
}
