// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: attribute-list.module.css

export type AttributeListColumns = '1' | '2' | '3' | '4' | '5' | '6';
export type AttributeListColumnSpan = '1' | '2' | '3' | '4' | '5' | '6';
export type AttributeListContentLineClamp = '1' | '2' | '3' | '4' | '5';

export interface AttributeListDataAttrs {
  columns?: AttributeListColumns;
  columnSpan?: AttributeListColumnSpan;
  contentLineClamp?: AttributeListContentLineClamp;
};

export namespace AttributeList {
  export type Columns = AttributeListColumns;
  export type ColumnSpan = AttributeListColumnSpan;
  export type ContentLineClamp = AttributeListContentLineClamp;
  export type DataAttrs = AttributeListDataAttrs;
}
