// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: checkbox-group.module.css

export type CheckboxGroupDirection = 'row';

export interface CheckboxGroupDataAttrs {
  direction?: CheckboxGroupDirection;
  disabled?: boolean;
  invalid?: boolean;
};

export namespace CheckboxGroup {
  export type Direction = CheckboxGroupDirection;
  export type DataAttrs = CheckboxGroupDataAttrs;
}
