// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: chip-input.module.css

export type ChipInputGap = '1' | '3' | '4';
export type ChipInputWrap = 'false';

export interface ChipInputDataAttrs {
  gap?: ChipInputGap;
  wrap?: ChipInputWrap;
  disabled?: boolean;
  hasIcon?: boolean;
  invalid?: boolean;
  selected?: boolean;
};

export namespace ChipInput {
  export type Gap = ChipInputGap;
  export type Wrap = ChipInputWrap;
  export type DataAttrs = ChipInputDataAttrs;
}
