// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: text-input.module.css

export type TextInputSize = 'large' | 'small';
export type TextInputVariant = 'filled' | 'ghost' | 'outline';

export interface TextInputDataAttrs {
  size?: TextInputSize;
  variant?: TextInputVariant;
  disabled?: boolean;
  hasLeading?: boolean;
  hasTrailing?: boolean;
  invalid?: boolean;
};

export namespace TextInput {
  export type Size = TextInputSize;
  export type Variant = TextInputVariant;
  export type DataAttrs = TextInputDataAttrs;
}
