// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
declare const styles: {
  readonly field: string;
  readonly input: string;
  readonly leading: string;
  readonly trailing: string;
  readonly wrapper: string;
};
export default styles;
