// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
declare const styles: {
  readonly field: string;
  readonly input: string;
  readonly 'left-icon': string;
  readonly 'right-icon': string;
  readonly wrapper: string;
};
export default styles;
