// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: filter-chip.module.css

export interface FilterChipDataAttrs {
  disabled?: boolean;
};

export namespace FilterChip {
  export type DataAttrs = FilterChipDataAttrs;
}
