// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: button-group.module.css

export type ButtonGroupGap = 'lg' | 'md' | 'sm' | 'xs';
export type ButtonGroupDirection = 'horizontal' | 'vertical';
export type ButtonGroupAlign = 'center' | 'end' | 'space-around' | 'space-between' | 'space-evenly' | 'start';
export type ButtonGroupWrap = 'nowrap' | 'wrap';

export interface ButtonGroupDataAttrs {
  gap?: ButtonGroupGap;
  direction?: ButtonGroupDirection;
  align?: ButtonGroupAlign;
  wrap?: ButtonGroupWrap;
};

export namespace ButtonGroup {
  export type Gap = ButtonGroupGap;
  export type Direction = ButtonGroupDirection;
  export type Align = ButtonGroupAlign;
  export type Wrap = ButtonGroupWrap;
  export type DataAttrs = ButtonGroupDataAttrs;
}
