// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: checkbox.module.css

export interface CheckboxDataAttrs {
  disabled?: boolean;
  invalid?: boolean;
  required?: boolean;
};

export namespace Checkbox {
  export type DataAttrs = CheckboxDataAttrs;
}
