// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: checkbox.module.css

export type CheckboxSize = 'large' | 'small';
export type CheckboxVariant = 'filled' | 'outline';

export interface CheckboxDataAttrs {
  size?: CheckboxSize;
  variant?: CheckboxVariant;
  disabled?: boolean;
  invalid?: boolean;
};

export namespace Checkbox {
  export type Size = CheckboxSize;
  export type Variant = CheckboxVariant;
  export type DataAttrs = CheckboxDataAttrs;
}
