// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: chip-multiple-input.module.css

export type ChipMultipleInputGap = '1' | '3' | '4';
export type ChipMultipleInputWrap = 'false';
export type ChipMultipleInputSize = 'large' | 'small';
export type ChipMultipleInputVariant = 'filled' | 'outline';

export interface ChipMultipleInputDataAttrs {
  gap?: ChipMultipleInputGap;
  wrap?: ChipMultipleInputWrap;
  size?: ChipMultipleInputSize;
  variant?: ChipMultipleInputVariant;
  disabled?: boolean;
  invalid?: boolean;
  selected?: boolean;
};

export namespace ChipMultipleInput {
  export type Gap = ChipMultipleInputGap;
  export type Wrap = ChipMultipleInputWrap;
  export type Size = ChipMultipleInputSize;
  export type Variant = ChipMultipleInputVariant;
  export type DataAttrs = ChipMultipleInputDataAttrs;
}
