// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
declare const styles: {
  readonly table: string;
  readonly 'table-body': string;
  readonly 'table-cell': string;
  readonly 'table-footer': string;
  readonly 'table-head': string;
  readonly 'table-header': string;
};
export default styles;
