// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: table.module.css

export type TableClickable = 'true';
export type TableVariant = 'action' | 'checkbox' | 'double-line' | 'highlight' | 'numeric';
export type TableSize = 'lg' | 'sm';

export interface TableDataAttrs {
  clickable?: TableClickable;
  variant?: TableVariant;
  size?: TableSize;
};

export namespace Table {
  export type Clickable = TableClickable;
  export type Variant = TableVariant;
  export type Size = TableSize;
  export type DataAttrs = TableDataAttrs;
}
