// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: table.module.css

export type TableSortable = 'true';
export type TableClickable = 'true';
export type TableTableCellVariant = 'action' | 'checkbox' | 'double-line' | 'highlight' | 'numeric';

export interface TableDataAttrs {
  sortable?: TableSortable;
  clickable?: TableClickable;
  tableCellVariant?: TableTableCellVariant;
};

export namespace Table {
  export type Sortable = TableSortable;
  export type Clickable = TableClickable;
  export type TableCellVariant = TableTableCellVariant;
  export type DataAttrs = TableDataAttrs;
}
