// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
declare const styles: {
  readonly action: string;
  readonly 'action-item': string;
  readonly 'action-trigger': string;
  readonly body: string;
  readonly col: string;
  readonly 'double-line-subtitle': string;
  readonly 'double-line-title': string;
  readonly footer: string;
  readonly header: string;
  readonly row: string;
  readonly table: string;
  readonly toolbar: string;
};
export default styles;
