// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: modal.module.css

export type ModalSize = 'large' | 'small';
export type ModalPosition = 'bottom' | 'center' | 'top';
export type ModalAlign = 'center' | 'end' | 'start';

export interface ModalDataAttrs {
  size?: ModalSize;
  position?: ModalPosition;
  align?: ModalAlign;
  modalFooter?: boolean;
  modalHeader?: boolean;
};

export namespace Modal {
  export type Size = ModalSize;
  export type Position = ModalPosition;
  export type Align = ModalAlign;
  export type DataAttrs = ModalDataAttrs;
}
