// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
declare const styles: {
  readonly checkbox: string;
  readonly indicator: string;
  readonly input: string;
  readonly label: string;
};
export default styles;
