// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: modal.module.css

export interface ModalDataAttrs {
  closing?: boolean;
  open?: boolean;
};

export namespace Modal {
  export type DataAttrs = ModalDataAttrs;
}
