// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: text-area.module.css

export type TextAreaResizable = 'false' | 'true';

export interface TextAreaDataAttrs {
  resizable?: TextAreaResizable;
  disabled?: boolean;
  invalid?: boolean;
  readOnly?: boolean;
};

export namespace TextArea {
  export type Resizable = TextAreaResizable;
  export type DataAttrs = TextAreaDataAttrs;
}
