// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: text-area.module.css

export type TextAreaSize = 'large' | 'small';
export type TextAreaVariant = 'filled' | 'ghost' | 'outline';
export type TextAreaResize = 'both' | 'horizontal' | 'none' | 'vertical';

export interface TextAreaDataAttrs {
  size?: TextAreaSize;
  variant?: TextAreaVariant;
  resize?: TextAreaResize;
  disabled?: boolean;
  invalid?: boolean;
};

export namespace TextArea {
  export type Size = TextAreaSize;
  export type Variant = TextAreaVariant;
  export type Resize = TextAreaResize;
  export type DataAttrs = TextAreaDataAttrs;
}
