// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: tabs.module.css

export type TabsState = 'active' | 'disabled';

export interface TabsDataAttrs {
  state?: TabsState;
  fullWidth?: boolean;
};

export namespace Tabs {
  export type State = TabsState;
  export type DataAttrs = TabsDataAttrs;
}
