// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
declare const styles: {
  readonly tabitem: string;
  readonly tablist: string;
  readonly tabs: string;
  readonly trigger: string;
};
export default styles;
