// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: radio.module.css

export type RadioSize = 'large' | 'small';
export type RadioVariant = 'filled' | 'outline';

export interface RadioDataAttrs {
  size?: RadioSize;
  variant?: RadioVariant;
  disabled?: boolean;
  invalid?: boolean;
};

export namespace Radio {
  export type Size = RadioSize;
  export type Variant = RadioVariant;
  export type DataAttrs = RadioDataAttrs;
}
