// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
declare const styles: {
  readonly 'bottom-bar': string;
  readonly 'bottom-bar-item': string;
  readonly 'bottom-bar-item-icon': string;
  readonly 'bottom-bar-item-text': string;
};
export default styles;
