// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: button.module.css

export type ButtonSize = 'large' | 'medium' | 'small';
export type ButtonVariant = 'danger' | 'primary' | 'secondary';

export interface ButtonDataAttrs {
  size?: ButtonSize;
  variant?: ButtonVariant;
  disabled?: boolean;
  loading?: boolean;
}

export namespace Button {
  export type Size = ButtonSize;
  export type Variant = ButtonVariant;
  export type DataAttrs = ButtonDataAttrs;
}
