// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: button.module.css

export type ButtonSize = 'large' | 'medium' | 'small';
export type ButtonVariant = 'danger' | 'ghost' | 'outline' | 'primary' | 'secondary';
export type ButtonLoadingIcon = 'loader';

export interface ButtonDataAttrs {
  size?: ButtonSize;
  variant?: ButtonVariant;
  loadingIcon?: ButtonLoadingIcon;
  disabled?: boolean;
  loading?: boolean;
};

export namespace Button {
  export type Size = ButtonSize;
  export type Variant = ButtonVariant;
  export type LoadingIcon = ButtonLoadingIcon;
  export type DataAttrs = ButtonDataAttrs;
}
