// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
declare const styles: {
  readonly chevron: string;
  readonly content: string;
  readonly group: string;
  readonly item: string;
  readonly label: string;
  readonly right: string;
  readonly trigger: string;
};
export default styles;
