// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: accordion.module.css

export interface AccordionDataAttrs {
  open?: boolean;
};

export namespace Accordion {
  export type DataAttrs = AccordionDataAttrs;
}
