// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: loader.module.css

export type LoaderType = 'bar' | 'spinner';
export type LoaderSize = 'lg' | 'sm';

export interface LoaderDataAttrs {
  type?: LoaderType;
  size?: LoaderSize;
};

export namespace Loader {
  export type Type = LoaderType;
  export type Size = LoaderSize;
  export type DataAttrs = LoaderDataAttrs;
}
