// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: sidebar.module.css

export interface SidebarDataAttrs {
  action?: boolean;
  active?: boolean;
  disabled?: boolean;
  expanded?: boolean;
};

export namespace Sidebar {
  export type DataAttrs = SidebarDataAttrs;
}
