// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: sidebar.module.css

export type SidebarOpen = 'false';

export interface SidebarDataAttrs {
  open?: SidebarOpen;
  active?: boolean;
  disabled?: boolean;
  focused?: boolean;
};

export namespace Sidebar {
  export type Open = SidebarOpen;
  export type DataAttrs = SidebarDataAttrs;
}
