// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
declare const styles: {
  readonly action: string;
  readonly 'additional-info': string;
  readonly header: string;
  readonly heading: string;
  readonly subtitle: string;
  readonly 'subtitle-additional-info': string;
  readonly 'subtitle-text': string;
  readonly supplementary: string;
  readonly title: string;
  readonly 'title-inner': string;
  readonly 'title-right': string;
};
export default styles;
