// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: page-header.module.css

export type PageHeaderAction = 'false' | 'true';
export type PageHeaderAdditionalInfo = 'false' | 'true';

export interface PageHeaderDataAttrs {
  action?: PageHeaderAction;
  additionalInfo?: PageHeaderAdditionalInfo;
};

export namespace PageHeader {
  export type Action = PageHeaderAction;
  export type AdditionalInfo = PageHeaderAdditionalInfo;
  export type DataAttrs = PageHeaderDataAttrs;
}
