// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: app-layout.module.css

export interface AppLayoutDataAttrs {
  centered?: boolean;
};

export namespace AppLayout {
  export type DataAttrs = AppLayoutDataAttrs;
}
