// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: app-layout.module.css

export type AppLayoutVariant = 'classic' | 'full' | 'mobile' | 'split';
export type AppLayoutPlacement = 'centred';

export interface AppLayoutDataAttrs {
  variant?: AppLayoutVariant;
  placement?: AppLayoutPlacement;
  hideBottom?: boolean;
  hideHeader?: boolean;
};

export namespace AppLayout {
  export type Variant = AppLayoutVariant;
  export type Placement = AppLayoutPlacement;
  export type DataAttrs = AppLayoutDataAttrs;
}
