// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: combobox-input.module.css

export type ComboboxInputPlacement = 'bottom' | 'top';

export interface ComboboxInputDataAttrs {
  placement?: ComboboxInputPlacement;
  active?: boolean;
  chevron?: boolean;
  disabled?: boolean;
  hasLeftIcon?: boolean;
  hasRightIcon?: boolean;
  invalid?: boolean;
  open?: boolean;
  placeholder?: boolean;
};

export namespace ComboboxInput {
  export type Placement = ComboboxInputPlacement;
  export type DataAttrs = ComboboxInputDataAttrs;
}
