// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
declare const styles: {
  readonly button: string;
  readonly 'button-content': string;
  readonly chips: string;
  readonly 'drawer-container': string;
  readonly 'drawer-input': string;
  readonly 'drawer-input-wrapper': string;
  readonly 'drawer-listbox': string;
  readonly field: string;
  readonly 'left-icon': string;
  readonly listbox: string;
  readonly 'listbox-inner': string;
  readonly option: string;
  readonly 'option-check': string;
  readonly 'right-icon': string;
  readonly root: string;
};
export default styles;
