// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
declare const styles: {
  readonly content: string;
  readonly field: string;
  readonly indicator: string;
  readonly input: string;
  readonly option: string;
};
export default styles;
