// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: selectable-input.module.css

export type SelectableInputPlacement = 'bottom' | 'center' | 'top';

export interface SelectableInputDataAttrs {
  placement?: SelectableInputPlacement;
  disabled?: boolean;
  invalid?: boolean;
  selected?: boolean;
};

export namespace SelectableInput {
  export type Placement = SelectableInputPlacement;
  export type DataAttrs = SelectableInputDataAttrs;
}
