// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: avatar.module.css

export type AvatarSize = 'lg' | 'md' | 'sm' | 'xl' | 'xs';
export type AvatarShape = 'circle' | 'square';
export type AvatarVariant = 'danger' | 'ghost' | 'outline' | 'primary' | 'secondary';

export interface AvatarDataAttrs {
  size?: AvatarSize;
  shape?: AvatarShape;
  variant?: AvatarVariant;
};

export namespace Avatar {
  export type Size = AvatarSize;
  export type Shape = AvatarShape;
  export type Variant = AvatarVariant;
  export type DataAttrs = AvatarDataAttrs;
}
