// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: avatar-group.module.css

export type AvatarGroupDirection = 'horizontal' | 'vertical';
export type AvatarGroupSize = 'lg' | 'md' | 'sm' | 'xl' | 'xs';

export interface AvatarGroupDataAttrs {
  direction?: AvatarGroupDirection;
  size?: AvatarGroupSize;
};

export namespace AvatarGroup {
  export type Direction = AvatarGroupDirection;
  export type Size = AvatarGroupSize;
  export type DataAttrs = AvatarGroupDataAttrs;
}
