// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: table.module.css

export type TableSortable = 'true';
export type TableAlign = 'center' | 'left' | 'right';
export type TableTableCellVariant = 'action' | 'checkbox' | 'double-line' | 'highlight' | 'numeric';

export interface TableDataAttrs {
  sortable?: TableSortable;
  align?: TableAlign;
  tableCellVariant?: TableTableCellVariant;
};

export namespace Table {
  export type Sortable = TableSortable;
  export type Align = TableAlign;
  export type TableCellVariant = TableTableCellVariant;
  export type DataAttrs = TableDataAttrs;
}
