// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: table.module.css

export type TableTableCellVariant = 'basic' | 'highlight' | 'numeric';

export interface TableDataAttrs {
  tableCellVariant?: TableTableCellVariant;
};

export namespace Table {
  export type TableCellVariant = TableTableCellVariant;
  export type DataAttrs = TableDataAttrs;
}
