// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: bottom-sheet.module.css

export interface BottomSheetDataAttrs {
  closing?: boolean;
  open?: boolean;
};

export namespace BottomSheet {
  export type DataAttrs = BottomSheetDataAttrs;
}
