// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: select.module.css

export interface SelectDataAttrs {
  disabled?: boolean;
  invalid?: boolean;
};

export namespace Select {
  export type DataAttrs = SelectDataAttrs;
}
