// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: select.module.css

export type SelectSize = 'large' | 'small';
export type SelectVariant = 'filled' | 'ghost' | 'outline';

export interface SelectDataAttrs {
  size?: SelectSize;
  variant?: SelectVariant;
  disabled?: boolean;
  invalid?: boolean;
};

export namespace Select {
  export type Size = SelectSize;
  export type Variant = SelectVariant;
  export type DataAttrs = SelectDataAttrs;
}
