// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: bottom-bar.module.css

export interface BottomBarDataAttrs {
  active?: boolean;
  disabled?: boolean;
  focused?: boolean;
};

export namespace BottomBar {
  export type DataAttrs = BottomBarDataAttrs;
}
