// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: top-bar.module.css

export type TopBarVariant = 'primary' | 'secondary';

export interface TopBarDataAttrs {
  variant?: TopBarVariant;
  active?: boolean;
};

export namespace TopBar {
  export type Variant = TopBarVariant;
  export type DataAttrs = TopBarDataAttrs;
}
