// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
declare const styles: {
  readonly 'top-bar': string;
  readonly 'top-bar-actions': string;
  readonly 'top-bar-leading': string;
  readonly 'top-bar-mobile-toggle': string;
  readonly 'top-bar-nav': string;
  readonly 'top-bar-nav-item': string;
  readonly 'top-bar-trailing': string;
};
export default styles;
