// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: utilities.module.css

export interface UtilitiesDataAttrs {
};

export namespace Utilities {
  export type DataAttrs = UtilitiesDataAttrs;
}
