// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
declare const styles: {
  readonly body: string;
  readonly card: string;
  readonly footer: string;
  readonly header: string;
};
export default styles;
