// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: card.module.css

export type CardSize = 'lg' | 'md' | 'sm' | 'xl' | 'xs';
export type CardShape = 'rounded' | 'square';
export type CardBordered = 'false' | 'true';
export type CardInteractive = 'false' | 'true';

export interface CardDataAttrs {
  size?: CardSize;
  shape?: CardShape;
  bordered?: CardBordered;
  interactive?: CardInteractive;
};

export namespace Card {
  export type Size = CardSize;
  export type Shape = CardShape;
  export type Bordered = CardBordered;
  export type Interactive = CardInteractive;
  export type DataAttrs = CardDataAttrs;
}
