// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
declare const styles: {
  readonly card: string;
  readonly 'card-avatar': string;
  readonly 'card-badge': string;
  readonly 'card-badge-group': string;
  readonly 'card-container': string;
  readonly 'card-content': string;
  readonly 'card-footer': string;
  readonly 'card-header': string;
  readonly 'card-list': string;
  readonly 'card-list-item': string;
  readonly 'card-subtitle': string;
  readonly 'card-supplementary': string;
  readonly 'card-title': string;
};
export default styles;
