// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: badge.module.css

export type BadgeIconConfig = 'both' | 'both-text' | 'left' | 'left-text' | 'right' | 'right-text';
export type BadgeSize = 'medium' | 'small';
export type BadgeVariant = 'danger' | 'info' | 'primary' | 'secondary' | 'success' | 'warning';
export type BadgeShape = 'pill' | 'rounded';

export interface BadgeDataAttrs {
  iconConfig?: BadgeIconConfig;
  size?: BadgeSize;
  variant?: BadgeVariant;
  shape?: BadgeShape;
};

export namespace Badge {
  export type IconConfig = BadgeIconConfig;
  export type Size = BadgeSize;
  export type Variant = BadgeVariant;
  export type Shape = BadgeShape;
  export type DataAttrs = BadgeDataAttrs;
}
