// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: text.module.css

export type TextAs = 'em' | 'label' | 'p' | 'small' | 'span' | 'strong';
export type TextSize = '2xl' | 'base' | 'lg' | 'sm' | 'xl' | 'xs';
export type TextWeight = 'bold' | 'medium' | 'normal' | 'semibold';
export type TextIntent = 'danger' | 'default' | 'muted' | 'success' | 'warning';

export interface TextDataAttrs {
  as?: TextAs;
  size?: TextSize;
  weight?: TextWeight;
  intent?: TextIntent;
};

export namespace Text {
  export type As = TextAs;
  export type Size = TextSize;
  export type Weight = TextWeight;
  export type Intent = TextIntent;
  export type DataAttrs = TextDataAttrs;
}
