// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: tooltip.module.css

export type TooltipPlacement = 'bottom' | 'left' | 'right' | 'top';

export interface TooltipDataAttrs {
  placement?: TooltipPlacement;
};

export namespace Tooltip {
  export type Placement = TooltipPlacement;
  export type DataAttrs = TooltipDataAttrs;
}
