// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: card.module.css

export type CardSize = 'lg' | 'md' | 'sm' | 'xl' | 'xs';
export type CardBorder = 'all-rounded' | 'bottom' | 'horizontal' | 'left' | 'right' | 'top' | 'vertical';
export type CardInteractive = 'false' | 'true';
export type CardJustify = 'around' | 'between' | 'center' | 'end' | 'start';
export type CardGap = 'lg' | 'md' | 'none' | 'sm' | 'xs';
export type CardAlign = 'center' | 'left' | 'right';

export interface CardDataAttrs {
  size?: CardSize;
  border?: CardBorder;
  interactive?: CardInteractive;
  justify?: CardJustify;
  gap?: CardGap;
  align?: CardAlign;
};

export namespace Card {
  export type Size = CardSize;
  export type Border = CardBorder;
  export type Interactive = CardInteractive;
  export type Justify = CardJustify;
  export type Gap = CardGap;
  export type Align = CardAlign;
  export type DataAttrs = CardDataAttrs;
}
