// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: drawer.module.css

export type DrawerPlacement = 'left' | 'right';

export interface DrawerDataAttrs {
  placement?: DrawerPlacement;
  closing?: boolean;
  open?: boolean;
};

export namespace Drawer {
  export type Placement = DrawerPlacement;
  export type DataAttrs = DrawerDataAttrs;
}
