// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: label.module.css

export interface LabelDataAttrs {
  disabled?: boolean;
  required?: boolean;
};

export namespace Label {
  export type DataAttrs = LabelDataAttrs;
}
