// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: attribute-list.module.css

export type AttributeListColumns = '1' | '2' | '3' | '4' | '5' | '6';
export type AttributeListSpan = '1' | '2' | '3' | '4' | '5' | '6';

export interface AttributeListDataAttrs {
  columns?: AttributeListColumns;
  span?: AttributeListSpan;
};

export namespace AttributeList {
  export type Columns = AttributeListColumns;
  export type Span = AttributeListSpan;
  export type DataAttrs = AttributeListDataAttrs;
}
