// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: kbd.module.css

export type KbdSize = 'lg' | 'md' | 'sm' | 'xs';
export type KbdVariant = 'filled' | 'ghost' | 'outline';

export interface KbdDataAttrs {
  size?: KbdSize;
  variant?: KbdVariant;
};

export namespace Kbd {
  export type Size = KbdSize;
  export type Variant = KbdVariant;
  export type DataAttrs = KbdDataAttrs;
}
