// AUTO-GENERATED by @versaur/tooling — DO NOT EDIT
// Source: heading.module.css

export type HeadingAs = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
export type HeadingSize = '2xl' | 'base' | 'lg' | 'sm' | 'xl' | 'xs';
export type HeadingWeight = 'bold' | 'medium' | 'normal' | 'semibold';
export type HeadingIntent = 'danger' | 'default' | 'muted' | 'success' | 'warning';

export interface HeadingDataAttrs {
  as?: HeadingAs;
  size?: HeadingSize;
  weight?: HeadingWeight;
  intent?: HeadingIntent;
};

export namespace Heading {
  export type As = HeadingAs;
  export type Size = HeadingSize;
  export type Weight = HeadingWeight;
  export type Intent = HeadingIntent;
  export type DataAttrs = HeadingDataAttrs;
}
